### ISSUE TITLE
希望能有帮助

### ISSUE THREAD

**Issue by LewisTian** [poverty-alleviation-team/bilibili-avatar-pendant#1]
本来是在Github找有没有人搜集b站的logo
然后看到这个项目，感觉也挺有趣的
于是写了个小爬虫，希望能有所帮助吧😂
https://github.com/LewisTian/Crawler#%E6%8C%82%E4%BB%B6%E5%9B%BE%E7%89%87%E7%88%AC%E5%8F%96

**Comment by lewky** [comment]
好的！！谢谢大佬，我最近在学习Java爬虫，也是想要爬取下b站的图片

**Comment by lewky** [comment]
@LewisTian 好的，谢谢大佬！！我最近在学习Java爬虫，也是想要爬取下b站的图片
